version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: crypto-alerts-api:latest
    container_name: crypto-alerts-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:example@db:5432/crypto_alerts
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app:cached
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: crypto-alerts-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: crypto-alerts-redis
    restart: always
    ports:
      - "6379:6379"

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: crypto-alerts-api:latest
    container_name: crypto-alerts-celery-beat
    command: celery -A app.core.celery_app:celery_app beat --loglevel=info
    env_file:
      - .env
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:example@db:5432/crypto_alerts
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app:cached
    depends_on:
      - redis
      - db

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: crypto-alerts-api:latest
    container_name: crypto-alerts-celery-worker
    command: celery -A app.core.celery_app:celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:example@db:5432/crypto_alerts
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app:cached
    depends_on:
      - redis
      - db

volumes:
  db-data:
