# docker-compose.yml
version: "3.8"

services:
  api:
    # Build the image from your Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    image: crypto-alerts-api:latest
    container_name: crypto-alerts-api
    # Run the FastAPI server
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    # Load environment variables (DB creds, JWT secret, etc.)
    env_file:
      - .env
    # Mount your code for live reload during development
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:example@db:5432/crypto_alerts

    volumes:
      - .:/app:cached
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: crypto-alerts-db
    restart: always
    environment:
      # These should match your `.env` entries
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # Persist data between restarts
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: crypto-alerts-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  # Named volume for Postgres data persistence
  db-data:
